rmarkdown::render(input = "ST 558 Project 2.Rmd",
                  output_format = "github_document",
                  output_file = "README.md",
                  output_options = list(
                    toc = TRUE, 
                    toc_depth = 3,
                    toc_float = TRUE,
                    code_folding = "show",
                    theme = "readable",
                    df_print = "paged"))