---
title: 'ST 558: Project 2'
author: "Chandler Ellsworth"
date: "2023-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, warning = FALSE)

```


```{r}
library(httr2)
library(jsonlite)
library(tidyverse)
```


```{r}
token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'

req <- request("https://api.collegefootballdata.com/venues") %>% 
  req_auth_bearer_token(token) %>% 
  req_headers("Accept" = "application/json")

mydata <- req_perform(req)

mydf <- fromJSON(rawToChar(mydata$body))

mytib <- as_tibble(mydf)

mytib %>%
  select(name, capacity, grass, city, state, elevation, year_constructed, dome)

```

```{r}
team_talent_composite_rankings <- function(year) {
  
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'
  
  url <- paste0("https://api.collegefootballdata.com/talent?year=",year)
  
  req <- request(url) %>% 
    req_auth_bearer_token(token) %>% 
    req_headers("Accept" = "application/json")
  
  mydata <- req_perform(req)
  
  mydf <- fromJSON(rawToChar(mydata$body))
  
  mytib <- as_tibble(mydf)
  
  return(mytib)

}

team_talent_composite_rankings(2018)

```


```{r}
coaching_history <- function(first_name, last_name) {
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'
  
  url <- paste0("https://api.collegefootballdata.com/coaches?firstName=",first_name,"&lastName=",last_name)
  
  req <- request(url) %>% 
    req_auth_bearer_token(token) %>% 
    req_headers("Accept" = "application/json")
  
  mydata <- req_perform(req)
  
  mydf <- fromJSON(rawToChar(mydata$body))$seasons
  
  mytib <- as_tibble(mydf[[1]])
  
  return(mytib)
}


coaching_history("Mack", "Brown")
```


```{r}
team_season_stats <- function(year, team) {
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'
  
  first_name <- word(team, 1)
  last_name <- word(team, 2)
  
  url <- ifelse(grepl(" ", team),
                paste0("https://api.collegefootballdata.com/stats/season?year=",
                       year,"&team=",first_name,"%20",last_name),
                paste0("https://api.collegefootballdata.com/stats/season?year=",
                       year,"&team=",team))
  
  req <- request(url) %>% 
    req_auth_bearer_token(token) %>% 
    req_headers("Accept" = "application/json")
  
  mydata <- req_perform(req)
  
  mydf <- fromJSON(rawToChar(mydata$body))
  
  mytib <- as_tibble(mydf)
  
  return(mytib)
}

team_season_stats(2019, "Texas")
```


```{r}
game_results <- function(year, team) {
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'
  
  first_name <- word(team, 1)
  last_name <- word(team, 2)
  
  url <- ifelse(grepl(" ", team),
                paste0("https://api.collegefootballdata.com/games?year=",
                       year,"&seasonType=regular&team=",first_name,"%20",last_name),
                paste0("https://api.collegefootballdata.com/games?year=",
                       year,"&seasonType=regular&team=",team))
  
  req <- request(url) %>% 
  req_auth_bearer_token(token) %>% 
  req_headers("Accept" = "application/json")

  mydata <- req_perform(req)

  mydf <- fromJSON(rawToChar(mydata$body))

  mytib <- as_tibble(mydf)

  mytib <- mytib %>%
    select(season, week, attendance, venue, home_team, home_points, away_team, away_points, excitement_index)
  
  return(mytib)
}

game_results(2019, "Ohio State")
```


```{r}
team_records <- function(year, team) {
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'
  
  first_name <- word(team, 1)
  last_name <- word(team, 2)
  
  url <- ifelse(grepl(" ", team),
                paste0("https://api.collegefootballdata.com/records?year=",
                       year,"&team=",first_name,"%20",last_name),
                paste0("https://api.collegefootballdata.com/records?year=",
                       year,"&team=",team))
  
  req <- request(url) %>% 
    req_auth_bearer_token(token) %>% 
    req_headers("Accept" = "application/json")

  mydata <- req_perform(req)

  mydf <- fromJSON(rawToChar(mydata$body))$total

  mytib <- as_tibble(mydf)
  
  return(mytib)
}

team_records(2022, "Ohio State")
```

```{r}
venue_info <- function(venue_name = NULL) {
  token <- 'L8SLuL2Jzi8KI5g0iHQYaERuCZgEDvyxDpOvDTgSqrLWvU7/8Yd5XuAPCfZJjMCJ'

  req <- request("https://api.collegefootballdata.com/venues") %>% 
    req_auth_bearer_token(token) %>% 
    req_headers("Accept" = "application/json")

  mydata <- req_perform(req)

  mydf <- fromJSON(rawToChar(mydata$body))

  mytib <- as_tibble(mydf)

  mytib <- mytib %>%
    select(name, capacity, grass, city, state, elevation, year_constructed, dome)
  
  ifelse(!is.null(venue_name),
         mytib <- mytib %>%
           filter(name == venue_name),
         NA)
  
  return(mytib)
}

venue_info("ACU Football Field")
```




